name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}

    strategy:
      matrix:
        sys:
          - { os: ubuntu-20.04, shell: bash }
          - { os: windows-latest, shell: 'msys2 {0}' }
          - { os: macos-11, shell: bash }

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt5 (Ubuntu)
      if: runner.os == 'Linux'
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb https://ppa.launchpadcontent.net/beineri/opt-qt-5.15.2-focal/ubuntu focal main
        repo-name: qt515
        keys: C65D51784EDC19A871DBDBB710C56D0DE9977759
        key-server: keyserver.ubuntu.com
        update: true
        install: qt515base qt515tools libgl-dev

    - name: Install MSYS2 and Qt5 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: gzip mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt5-static mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-nsis

    - name: Install Qt5 (Mac OS)
      if: runner.os == 'macos'
      run: brew install qt@5

    # On Windows we need to fix the path to the workspace so MSYS can use it. Use an environment
    # variable for that.
    - name: Fixup workspace path (Windows)
      if: runner.os == 'Windows'
      run: echo "fixed_workspace=`cygpath -u '${{github.workspace}}'`" >> $GITHUB_ENV
    - name: Propagate workspace path
      if: runner.os != 'Windows'
      run: echo "fixed_workspace='${{github.workspace}}'" >> $GITHUB_ENV

    - name: Configure (Ubuntu and Windows)
      if: runner.os != 'macos'
      run: cmake -B ${{env.fixed_workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Configure (Mac OS)
      if: runner.os == 'macos'
      run: cmake -B ${{env.fixed_workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        Qt5_DIR: /usr/local/opt/qt5/lib/cmake

    - name: Build
      run: cmake --build ${{env.fixed_workspace}}/build --config ${{env.BUILD_TYPE}} -j2
